# Generated by Django 5.2.11 on 2026-02-09

from django.db import migrations, models
import uuid


def populate_serial_numbers(apps, schema_editor):
    Component = apps.get_model('inventory', 'Component')
    for component in Component.objects.filter(serial_number__isnull=True) | Component.objects.filter(serial_number=''):
        component.serial_number = f"SN-{uuid.uuid4().hex[:8].upper()}"
        component.save()


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_remove_transaction_borrower_name_beneficiary_and_more'),
    ]

    operations = [
        # First, populate empty serial numbers
        migrations.RunPython(populate_serial_numbers, migrations.RunPython.noop),
        
        # Now make category name unique
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        
        # Make serial_number non-nullable and unique
        migrations.AlterField(
            model_name='component',
            name='serial_number',
            field=models.CharField(help_text='Unique identifier for this component', max_length=100, unique=True),
        ),
    ]
