# Generated by Django 5.2.11 on 2026-02-09

from django.db import migrations, models


def populate_defaults(apps, schema_editor):
    Beneficiary = apps.get_model('inventory', 'Beneficiary')
    for beneficiary in Beneficiary.objects.all():
        beneficiary.category = 'Other'
        beneficiary.phone_number = '000-000-0000'
        beneficiary.save()


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_add_unique_serial_number'),
    ]

    operations = [
        # Add new fields
        migrations.AddField(
            model_name='beneficiary',
            name='category',
            field=models.CharField(choices=[('Employee', 'Employee'), ('Student', 'Student'), ('Intern', 'Intern'), ('Other', 'Other')],default='Other', max_length=20),
        ),
        migrations.AddField(
            model_name='beneficiary',
            name='employee_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='beneficiary',
            name='phone_number',
            field=models.CharField(default='000-000-0000', max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='beneficiary',
            name='stream',
            field=models.CharField(blank=True, choices=[('BCA', 'BCA'), ('AI & Robotics', 'AI & Robotics')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='beneficiary',
            name='student_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        
        # Run data migration
        migrations.RunPython(populate_defaults, migrations.RunPython.noop),
        
        # Update __str__ method by altering the model
        migrations.AlterModelOptions(
            name='beneficiary',
            options={'verbose_name_plural': 'Beneficiaries'},
        ),
    ]
