# Generated by Django 5.2.11 on 2026-02-25 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_sale'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='notes',
            field=models.TextField(blank=True, help_text='Optional description or notes', null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='notes',
            field=models.TextField(blank=True, help_text='Optional description or notes', null=True),
        ),
    ]
