# Generated by Django 5.2.11 on 2026-03-09 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_sale_notes_transaction_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='component',
            name='low_stock_dismissed',
            field=models.BooleanField(default=False, help_text='If True, this component is excluded from the low-stock warning panel'),
        ),
    ]
