# Generated by Django 5.2.11 on 2026-02-26 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_sale_notes_transaction_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='component',
            name='component_type',
            field=models.CharField(choices=[('GENERAL', 'General Component'), ('KIT', 'General Kit')], default='GENERAL', max_length=10),
        ),
    ]
