# Generated by Django 5.2.11 on 2026-03-17 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_component_component_type'),
        ('inventory', '0009_component_low_stock_dismissed'),
    ]

    operations = [
    ]
