# Generated by Django 5.2.11 on 2026-04-06 07:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_merge_20260317_1243'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='component',
            name='low_stock_dismissed',
        ),
        migrations.CreateModel(
            name='KitItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('quantity', models.IntegerField(default=1)),
                ('kit', models.ForeignKey(limit_choices_to={'component_type': 'KIT'}, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.component')),
            ],
        ),
    ]
