# Generated by Django 5.2.11 on 2026-04-07 05:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_remove_component_low_stock_dismissed_kititem'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralKitItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(help_text='Unique identifier for this item', max_length=100, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('count', models.IntegerField(default=0, help_text='Current quantity available')),
                ('description', models.TextField(blank=True)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='general_kit_items', to='inventory.category')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
