# Generated by Django 5.2.11 on 2026-04-07 07:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_generalkititem'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='general_kit_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='inventory.generalkititem'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='component',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.component'),
        ),
    ]
